task1

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,13 +1,26 @@
 #!/usr/bin/env bash
+# This script transfers a file from a client to a server using scp.
 
-if [ $# -lt 3 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+# Check if all required parameters are provided
+if [ "$#" -ne 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-file=$1
-ip=$2 
-user=$3
-key=$4
+# Assign parameters to variables
+PATH_TO_FILE="$1"
+IP="$2"
+USERNAME="$3"
+PATH_TO_SSH_KEY="$4"
 
-scp -o StrictHostKeyChecking=no "$file" "$user@$ip:~" < "/dev/null" 2>&1
+# Use scp to transfer the file to the server's home directory (~)
+# Disable strict host key checking with "-o StrictHostKeyChecking=no"
+scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
+
+# Check if the scp command was successful
+if [ "$?" -eq 0 ]; then
+  echo "File transfer successful."
+else
+  echo "File transfer failed."
+  exit 1
+fi
